name: Generate LaTeX Documentation
on: [push]
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Passage en v4 pour checkout Ã©galement

      - name: Markdown to PDF
        uses: docker://pandoc/extra:latest
        with:
          args: >-
            --standalone
            --output=Doc/documentation.pdf
            Doc/documentation.md

      - name: Upload result
        uses: actions/upload-artifact@v4 # LA CORRECTION EST ICI
        with:
          name: Rapport-Final
          path: Doc/documentation.pdf
